format_version: 3
pipelines:
  greenhouseProject:
    lock_behavior: lockOnFailure
    group: green
    materials:
      repo:
        git: https://github.com/devops-at06/AG_GreenHouse.git
        branch: master
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"  
                     
              artifacts:
                - build:
                    source: build/libs/*.war
                    destination: buildJar   
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
                - exec:
                    command: ./gradlew
                    arguments:
                      - jacocoTestReport
                - exec:
                    command: ./gradlew
                    arguments:
                      - check
              artifacts:
                - build:
                    source: build/reports/tests/test/index.html
                    destination: html
                - build:
                    source: build/reports/findbugs/main.html
                    destination: findbugs
                - build:
                    source: build/jacoco/jacocoHtml/index.html
                    destination: coverage
                - build:
                    source: build/reports/pmd/main.html
                    destination: pmd
                - test:
                    source: build/reports/test-results/test/*.xml
                    destination: xml

              tabs:
                coverage: coverage/index.html
                findbugs_main: findbugs/main.html
                pmd_main: pmd/main.html
                htmlReports: html/index.html 

      - CodeQuality:
          jobs:
            CodeQuality: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - sonarqube
                    
